### ISSUE TITLE
[Bug] 400 Error when simulating Transactions on Optimism

### ISSUE THREAD

**Issue by DevDuki** [GetAurox/Aurox-Wallet#12]
I've been doing normal dApp interactions on 1inch and Stargate and everytime when I simulated the transaction, I got the error shown below.

Wallet v1.1.0

![image](https://user-images.githubusercontent.com/72626889/232413789-0c5d576d-92a2-4f15-a708-0f9597bc82b6.png)

**Comment by AuroxDeFi** [comment]
Thanks for reporting the issue. It was resolved in v1.2.1 that was released today.
