### ISSUE TITLE
[Bug] Rename 'Add Network' to 'Manage Networks'

### ISSUE THREAD

**Issue by AlexanderKoehn** [GetAurox/Aurox-Wallet#14]
Under 'My Aurox' -> 'Settings' -> 'Networks' the button at the bottom should be named 'Manage Networks' instead of 'Add Network', which is misleading and prevents people from clicking when they want to remove/uncheck a network.

Wallet Version 1.1.0

**Comment by AuroxDeFi** [comment]
Thanks for reporting the issue. It was resolved in 1.2.1 that was released today.

<img width="414" alt="HGJk84Pm7Rz3OWOCP0W339zcLj1T5PiseyqFQGtovvuyBV5leapZnAbbENqpIJsNed4ZfLbfWleqaOpJBKyiPdux1KeJ7O8TnnIj" src="https://github.com/GetAurox/Aurox-Wallet/assets/77427021/3efb459f-915b-43d7-9de3-5cc1a185aa3e">
