### ISSUE TITLE
[Bug] Trezor Hardware Wallet Connect Issue

### ISSUE THREAD

**Issue by scottnofriend** [GetAurox/Aurox-Wallet#15]
Hi Team,

Firstly, thank you for creating Aurox. I'm in love.
There's just one annoying bug with Trezor connectivity.
When I first connected my Trezor to Aurox I had to sign the Trezor pop up and eneter my passphrase (all totally understandbale and fine)
However, now whenever I connect to a dapp I am constantly bombarded with repeating Trezor pop ups asking me to sign.
This is not normal, and not neccessary for connecting to dapps. 
I have been simply closing the pop up windows and Aurox will still connect my Trezor wallet to the dapps.
This is more annoying than anything, I don'tt see it as a security risk, but please can devs create a fix?

Many thanks,
Scott

**Comment by AuroxDeFi** [comment]
Hi Scott,

Thanks for reporting the issue. Seems like there was a regression bug. 

This has been resolved in 1.2.1 that was released today.
