### ISSUE TITLE
[Bug] alert popups like "mailto" links are unreachable

### ISSUE THREAD

**Issue by DevDuki** [GetAurox/Aurox-Wallet#5]
The current "mailto" anchor tags create a popups which currently are placed very awkwardly (see screenshot). Sometimes the buttons can't even be reached, thus the user isn't able to click it away or use the wallet anymore and is forced to close and reopen it, leading to bad UX.

![image](https://user-images.githubusercontent.com/72626889/229131188-145d46b7-ff2f-41c6-956d-938391f36ca8.png)

So since these popups cannot be modified and are Browser dependant, my suggestion would be to add attributes `target="_blank" rel="noopener noreferrer"` to all links that create these kind of alert popups. These popups would then appear on a separate new browser's tab, instead of directly within the extension window itself. This on the other hand will close the wallet again, which is maybe not desired, but at least the user feels less "stuck".

An other suggestion would be to instead of using "mailto", simply copy the mail address to the user's clipboard (similarly to the wallet address). The only flaw here is that the user will feel less inclined to do the extra step and to actually go open up their mail app and paste the address manually.

What do you guys think?

**Comment by AuroxDeFi** [comment]
Where does this issue happen? 

The support email address in the about section isn't clickable on Chrome. Maybe the browser you're using automatically adds hyperlinks to emails? If so, which browser are you using?

**Comment by DevDuki** [comment]
One way to get to this error page is by following this issue #7 . The mail in the error is an anchor tag with an attribute of `href="mailto:[aurox's mail]"`, which when a user has set up a dedicated mail app on his computer, will force it to open, but first the browser will ask the user, if they want Aurox's Extension to allow opening the said mail app. For example the standard mail app in macOS. Users who use a browser based mail, will have it immediately open in a new tab. So whether this prompt opens or not is dependant on how the user has set up his email. 

More info about this here: https://css-tricks.com/all-about-mailto-links/#aa-open-in-new-tab-sometimes-does-matter

But yea you're right, the email link in the about section is just a copy-able text, which could be reused in these error messages!

**Comment by DevDuki** [comment]
Cannot be reproduced in V1.2.0, thus closing this issue.
