### ISSUE TITLE
[Bug] typo in unoswap from GraphQL backend

### ISSUE THREAD

**Issue by DevDuki** [GetAurox/Aurox-Wallet#6]
There is a typo coming from the GraphQL backend (I assume it's Aurox's backend) saying "unoswap" instead of "uniswap" (see screenshot)

![image](https://user-images.githubusercontent.com/72626889/229142038-6c92f81f-9de8-4a61-82cf-467f88763b0e.png)

**Comment by AuroxDeFi** [comment]
This isn't a typo. It's the function name of the contract the wallet interacted with. Specifically, it's 1inch's contract. For example:

https://etherscan.io/tx/0x330f0c6c21c2ecd02ef6a3305e96f66fdce161ffc280fef1765bcebf8ec4c506

The main way to fix this is if we integrated the protocol and properly parsed the data payload to display more human readable information. We're working on a solution right now to add protocols quickly. Each one is unique, and it can be time consuming to add right now.
