### ISSUE TITLE
[Bug] cannot read 'toString' of undefined in transaction details view

### ISSUE THREAD

**Issue by DevDuki** [GetAurox/Aurox-Wallet#7]
Use Case:
I send tokens from my Aurox Wallet to any other Wallet (can be any token too). I want to check that transaction in the transactions tab to see its details.

Current behavior:
The details view appears normal at first and no error occurs. However, after a while when opening the exact same transaction I get an undefined error (see screenshot). It is weird though, because I do not get this error after closing and reopening the wallet or after locking and unlocking it or anything else to actively trigger this bug. It seems like it's just that after a few minutes suddenly the state of that transaction has changed, which causes the `toString()` to be called on an undefined object.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/72626889/229152430-1cadbf67-8975-41b8-bd93-89dc7cb206dc.png">

Expected behavior:
No matter when I open the transaction details view of my sent token, it should always appear the same way as it does in the beginning.

How to reproduce:
When on the Home screen, click on any token, click Send and send to any other wallet. Wait for some minutes (i don't know exactly how long, an other option would be to just click "update" in the chrome extensions page). Reopen the wallet, go to Transactions tab, click the transaction with the "Sent [Token]" title. You should now see the error like in the screenshot above.

Additional Information:
Wallet Version: 1.0.6
Browser: Brave [Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (x86_64)]
OS: macOS Ventura 13.2.1

What I found out is that in `src/ui/common/transactions.ts` in the function `mapTokenTransactionToTokenTransactionDetails` line 303 (`const gasLimitHexString = (tx.transaction.gasLimit as unknown as BigNumberTyped).hex;`), we do not always get the exact object that we expect. The object `tx.transaction.gasLimit` gets casted to `BigNumberTyped` before its property `hex` is accessed, but that's exactly where the issue lies. I compared this object from before the bug occurs with the one when the bug occurs and they are slightly different (see screenshots below). The property `hex` doesn't exist, which returns undefined and using `Number(undefined)` returns `"NaN"` which has no `toString()` method, hence the error message.

`tx.transaction.gasLimit` before bug:
![image](https://user-images.githubusercontent.com/72626889/229155769-ab848be3-371a-4fdf-aab2-6061090f0520.png)

`tx.transaction.gasLimit` after the bug:
![image](https://user-images.githubusercontent.com/72626889/229155691-db1ed135-959e-4965-916c-ba8117ed0867.png)

So it seems like the transactions are fetched either from different endpoints or the endpoint it is fetched from is not consistent with the expected type of `BigNumberTyped`, because the same difference happens to the other properties that are casted to `BigNumberTyped` (i.e. `tx.transaction.gasPrice`).

So I assume this bug needs to be fixed on the server side rather than on the extension side, to ensure consistency of the data returned by the server.

**Comment by AuroxDeFi** [comment]
Thanks for reporting this with such details. We did an issue that was causing a similar crash and it will be rolled out in the upcoming release. Our devs are double checking to make sure our fix applies to this specific case.

**Comment by AuroxDeFi** [comment]
This issue should be resolved on release v1.1.0

We will leave this issue open for a week just to make sure it was resolved for everyone else.
